//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAddin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestAddin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to query data sources..
        /// </summary>
        internal static string CannotQueryDataSources {
            get {
                return ResourceManager.GetString("CannotQueryDataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to query handlers..
        /// </summary>
        internal static string CannotQueryHandlers {
            get {
                return ResourceManager.GetString("CannotQueryHandlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to query index servers..
        /// </summary>
        internal static string CannotQueryIndexServers {
            get {
                return ResourceManager.GetString("CannotQueryIndexServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}..
        /// </summary>
        internal static string ConnectingToHostname {
            get {
                return ResourceManager.GetString("ConnectingToHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during datasource creation; no new datasource was created.
        ///Error message: {0}.
        /// </summary>
        internal static string CreateErrorText {
            get {
                return ResourceManager.GetString("CreateErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Instead.
        /// </summary>
        internal static string CreateInstead {
            get {
                return ResourceManager.GetString("CreateInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Datasource.
        /// </summary>
        internal static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of the new datasource below..
        /// </summary>
        internal static string CreateNewDatasourceName {
            get {
                return ResourceManager.GetString("CreateNewDatasourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create what kind of datasource?.
        /// </summary>
        internal static string CreateNewDatasourceType {
            get {
                return ResourceManager.GetString("CreateNewDatasourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On which index server should the new datasource be located?.
        /// </summary>
        internal static string CreateNewWhatIndexServer {
            get {
                return ResourceManager.GetString("CreateNewWhatIndexServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during data posting; data source created but no data added.
        ///Error message: {0}.
        /// </summary>
        internal static string CreatePostErrorText {
            get {
                return ResourceManager.GetString("CreatePostErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasource successfully created. Spreadsheet data successfully posted..
        /// </summary>
        internal static string CreateSuccess {
            get {
                return ResourceManager.GetString("CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commvault Excel Data Cube Saved Credentials.
        /// </summary>
        internal static string CredComment {
            get {
                return ResourceManager.GetString("CredComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commvault_exceldatacubeaddin_savedlogin.
        /// </summary>
        internal static string CredName {
            get {
                return ResourceManager.GetString("CredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        internal static string CSV {
            get {
                return ResourceManager.GetString("CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Cube.
        /// </summary>
        internal static string DataCube {
            get {
                return ResourceManager.GetString("DataCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your dataset has failed the pre-export type validation check.
        ///Some values in your data are inconsistent with the server-side schema in place on the data source.
        ///Please check over the schema now and try again after adjusting your data..
        /// </summary>
        internal static string DataFailedTypeCheck {
            get {
                return ResourceManager.GetString("DataFailedTypeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Check Failed.
        /// </summary>
        internal static string DataFailedTypeCheckCaption {
            get {
                return ResourceManager.GetString("DataFailedTypeCheckCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        internal static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some date data in this set falls outside the bounds of the numerical datatype used to store it. These offending dates have been converted to textual data to preserve precision..
        /// </summary>
        internal static string DateOOBWarning {
            get {
                return ResourceManager.GetString("DateOOBWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Data Stringified.
        /// </summary>
        internal static string DateOOBWarningCaption {
            get {
                return ResourceManager.GetString("DateOOBWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eloqua.
        /// </summary>
        internal static string Eloqua {
            get {
                return ResourceManager.GetString("Eloqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header contains non-string value!.
        /// </summary>
        internal static string ErrNonTextHeader {
            get {
                return ResourceManager.GetString("ErrNonTextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of your headers contain non-alphanumeric characters which are not allowed in a field name.
        ///Please choose different field names..
        /// </summary>
        internal static string ErrorHeadersNeedAlphaNumericChars {
            get {
                return ResourceManager.GetString("ErrorHeadersNeedAlphaNumericChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error message.
        /// </summary>
        internal static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message.
        /// </summary>
        internal static string ErrorMsgCaps {
            get {
                return ResourceManager.GetString("ErrorMsgCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchemaModel values are not of type DSFieldType and cannot be jsonified!.
        /// </summary>
        internal static string ErrSchemaModelInvalidUsage {
            get {
                return ResourceManager.GetString("ErrSchemaModelInvalidUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel cannot store more than {0} columns..
        /// </summary>
        internal static string ErrTooManyColumns {
            get {
                return ResourceManager.GetString("ErrTooManyColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addin does not support Excel conversions to type {0}.
        /// </summary>
        internal static string ErrUnsupportedType {
            get {
                return ResourceManager.GetString("ErrUnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught while processing logon on server [{0}]: [{1}].
        /// </summary>
        internal static string ExceptionInLogon {
            get {
                return ResourceManager.GetString("ExceptionInLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Data Cube.
        /// </summary>
        internal static string ExportDataCube {
            get {
                return ResourceManager.GetString("ExportDataCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExportFlavorText {
            get {
                return ResourceManager.GetString("ExportFlavorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Instead.
        /// </summary>
        internal static string ExportInstead {
            get {
                return ResourceManager.GetString("ExportInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Federated Search.
        /// </summary>
        internal static string FederatedSearch {
            get {
                return ResourceManager.GetString("FederatedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System.
        /// </summary>
        internal static string FileSystem {
            get {
                return ResourceManager.GetString("FileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Credentials.
        /// </summary>
        internal static string ForgetCreds {
            get {
                return ResourceManager.GetString("ForgetCreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler.
        /// </summary>
        internal static string Handler {
            get {
                return ResourceManager.GetString("Handler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hostname.
        /// </summary>
        internal static string Hostname {
            get {
                return ResourceManager.GetString("Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname.
        /// </summary>
        internal static string HostnameCaps {
            get {
                return ResourceManager.GetString("HostnameCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP.
        /// </summary>
        internal static string HTTP {
            get {
                return ResourceManager.GetString("HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Data Cube.
        /// </summary>
        internal static string ImportDataCube {
            get {
                return ResourceManager.GetString("ImportDataCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImportFlavorText {
            get {
                return ResourceManager.GetString("ImportFlavorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Server.
        /// </summary>
        internal static string IndexServer {
            get {
                return ResourceManager.GetString("IndexServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP.
        /// </summary>
        internal static string LDAP {
            get {
                return ResourceManager.GetString("LDAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all data sources.
        /// </summary>
        internal static string ListAllDataSources {
            get {
                return ResourceManager.GetString("ListAllDataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This workbook has one or more worksheets which cannot be synchronized with the server you are currently logged into..
        /// </summary>
        internal static string LiveWorkbookSyncError {
            get {
                return ResourceManager.GetString("LiveWorkbookSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing. {0} out of {1} complete..
        /// </summary>
        internal static string LoadingBarText {
            get {
                return ResourceManager.GetString("LoadingBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Entities.
        /// </summary>
        internal static string LoadingFormTitle {
            get {
                return ResourceManager.GetString("LoadingFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout from Data Cube.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a live worksheet.
        /// </summary>
        internal static string MakeLiveWorksheet {
            get {
                return ResourceManager.GetString("MakeLiveWorksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAS.
        /// </summary>
        internal static string NAS {
            get {
                return ResourceManager.GetString("NAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the hostname of the webconsole server to continue logging in..
        /// </summary>
        internal static string NeedHostname {
            get {
                return ResourceManager.GetString("NeedHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new sheet will be created for this import..
        /// </summary>
        internal static string NewSheet {
            get {
                return ResourceManager.GetString("NewSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new workbook will be created..
        /// </summary>
        internal static string NewWorkbook {
            get {
                return ResourceManager.GetString("NewWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have a workbook loaded to export..
        /// </summary>
        internal static string NoActiveWorkbook {
            get {
                return ResourceManager.GetString("NoActiveWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected datasource seems to have no data assiociated with it..
        /// </summary>
        internal static string NoDataMessage {
            get {
                return ResourceManager.GetString("NoDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have a data source selected in order to import..
        /// </summary>
        internal static string NoDataSourceSelected {
            get {
                return ResourceManager.GetString("NoDataSourceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not logged in..
        /// </summary>
        internal static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some numeric data was explicitly converted to text in order to preserve precision..
        /// </summary>
        internal static string NumTextWarning {
            get {
                return ResourceManager.GetString("NumTextWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Conversion.
        /// </summary>
        internal static string NumTextWarningCaption {
            get {
                return ResourceManager.GetString("NumTextWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Data Source.
        /// </summary>
        internal static string OpenDataSource {
            get {
                return ResourceManager.GetString("OpenDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string PlaceholderText {
            get {
                return ResourceManager.GetString("PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to interact with data form Data Cube, please login..
        /// </summary>
        internal static string PleaseLogin {
            get {
                return ResourceManager.GetString("PleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during data posting; no data was posted to the datasource.
        ///Error message: {0}.
        /// </summary>
        internal static string PostErrorText {
            get {
                return ResourceManager.GetString("PostErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data successfully posted..
        /// </summary>
        internal static string PostSuccess {
            get {
                return ResourceManager.GetString("PostSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your credentials to continue..
        /// </summary>
        internal static string PromptEnterCreds {
            get {
                return ResourceManager.GetString("PromptEnterCreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught while executing rest API [{0}] on host [{1}]. Error message: {2}..
        /// </summary>
        internal static string RestApiExceptionText {
            get {
                return ResourceManager.GetString("RestApiExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesforce.
        /// </summary>
        internal static string Salesforce {
            get {
                return ResourceManager.GetString("Salesforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to log you in using your saved credentials. To continue, please login again..
        /// </summary>
        internal static string SavedLoginFailure {
            get {
                return ResourceManager.GetString("SavedLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data failed to validate against the datasource&apos;s schema. No data was posted..
        /// </summary>
        internal static string SchemaValidationFailure {
            get {
                return ResourceManager.GetString("SchemaValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Verification Required.
        /// </summary>
        internal static string SchemaVerificationRequired {
            get {
                return ResourceManager.GetString("SchemaVerificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only these types of data source.
        /// </summary>
        internal static string ShowOnlyTheseTypes {
            get {
                return ResourceManager.GetString("ShowOnlyTheseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some data was truncated while importing.
        ///Fields with length over 32,767 were automatically shortened to fit..
        /// </summary>
        internal static string TruncationWarning {
            get {
                return ResourceManager.GetString("TruncationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Truncated.
        /// </summary>
        internal static string TruncationWarningCaption {
            get {
                return ResourceManager.GetString("TruncationWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string TypeBoolean {
            get {
                return ResourceManager.GetString("TypeBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cell which failed the type check is {0}.
        ///The expected type was {1} but {0} had a {2} in it..
        /// </summary>
        internal static string TypeCheckConflictNotification {
            get {
                return ResourceManager.GetString("TypeCheckConflictNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string TypeDate {
            get {
                return ResourceManager.GetString("TypeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        internal static string TypeDouble {
            get {
                return ResourceManager.GetString("TypeDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float.
        /// </summary>
        internal static string TypeFloat {
            get {
                return ResourceManager.GetString("TypeFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string TypeInteger {
            get {
                return ResourceManager.GetString("TypeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        internal static string TypeLong {
            get {
                return ResourceManager.GetString("TypeLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long String.
        /// </summary>
        internal static string TypeLongString {
            get {
                return ResourceManager.GetString("TypeLongString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowercase String.
        /// </summary>
        internal static string TypeLowercaseString {
            get {
                return ResourceManager.GetString("TypeLowercaseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string TypeString {
            get {
                return ResourceManager.GetString("TypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TypeText {
            get {
                return ResourceManager.GetString("TypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string TypeTimestamp {
            get {
                return ResourceManager.GetString("TypeTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An operation failed and is unable to continue..
        /// </summary>
        internal static string UnableToContinue {
            get {
                return ResourceManager.GetString("UnableToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to properly pull the data from the server.
        ///Error: {0}.
        /// </summary>
        internal static string UnableToGetRemoteData {
            get {
                return ResourceManager.GetString("UnableToGetRemoteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to properly pull the data from the server..
        /// </summary>
        internal static string UnableToGetRemoteDataAmbiguous {
            get {
                return ResourceManager.GetString("UnableToGetRemoteDataAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to properly pull the data from the server..
        /// </summary>
        internal static string UnableToGetRemoteDataNoParam {
            get {
                return ResourceManager.GetString("UnableToGetRemoteDataNoParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve schema for validation..
        /// </summary>
        internal static string UnableToRetrieveSchema {
            get {
                return ResourceManager.GetString("UnableToRetrieveSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while updating the schema for the newly created data source.
        ///The data source was created but the schema could not be updated. No data was posted.
        ///Error: {0}.
        /// </summary>
        internal static string UnableToUpdateRemoteSchema {
            get {
                return ResourceManager.GetString("UnableToUpdateRemoteSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown API &quot;{0}&quot; --&gt; unable to resolve HttpMethod..
        /// </summary>
        internal static string UnknownAPIException {
            get {
                return ResourceManager.GetString("UnknownAPIException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use an Existing Datasource.
        /// </summary>
        internal static string UseExisting {
            get {
                return ResourceManager.GetString("UseExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to this datasource:.
        /// </summary>
        internal static string UseExistingDataSource {
            get {
                return ResourceManager.GetString("UseExistingDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by index server:.
        /// </summary>
        internal static string UseExistingIndexServer {
            get {
                return ResourceManager.GetString("UseExistingIndexServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit search results to this type of datasource:.
        /// </summary>
        internal static string UseExistingTypeFilterText {
            get {
                return ResourceManager.GetString("UseExistingTypeFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Validation Required.
        /// </summary>
        internal static string UserSchemaValidationFormTitle {
            get {
                return ResourceManager.GetString("UserSchemaValidationFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use selected region instead of whole file..
        /// </summary>
        internal static string UseSelectedRegion {
            get {
                return ResourceManager.GetString("UseSelectedRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify that each column&apos;s type is correct before proceeding..
        /// </summary>
        internal static string ValidationCreateNew {
            get {
                return ResourceManager.GetString("ValidationCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data types were inferred for the following unknown columns.
        ///Please ensure that the correct data types are listed below before clicking continue..
        /// </summary>
        internal static string ValidationUseExistingNEWCOLUMNS {
            get {
                return ResourceManager.GetString("ValidationUseExistingNEWCOLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webconsole Hostname:.
        /// </summary>
        internal static string WebconsoleHostname {
            get {
                return ResourceManager.GetString("WebconsoleHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll use this sheet for the import..
        /// </summary>
        internal static string WeWillUseThisSheet {
            get {
                return ResourceManager.GetString("WeWillUseThisSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The synchronized worksheet {0} is out of date.
        ///Did you want to pull down updated data from {1} now?.
        /// </summary>
        internal static string WorkbookOpenSyncNotification {
            get {
                return ResourceManager.GetString("WorkbookOpenSyncNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be logged out after 30 minutes of inactivity..
        /// </summary>
        internal static string YouWillBeLoggedOut {
            get {
                return ResourceManager.GetString("YouWillBeLoggedOut", resourceCulture);
            }
        }
    }
}
